<a href="https://colab.research.google.com/github/pu-bi/Python-study/blob/main/Gurogu%20Data%20Academy/1_Python_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<br>

#### 0. 특정 함수에 대해 궁금할 때

In [1]:
# 이것은 주석입니다.

In [2]:
print() # Shift+Tap

<br>

#### 1. 기초 데이터 타입

#### 정수형(integer)과 실수형(floats)

In [3]:
x = 3

In [4]:
x

3

In [5]:
type(x)

int

In [6]:
x+1

4

In [7]:
x*2

6

In [8]:
x**2

9

In [9]:
x += 1
x

4

In [10]:
x *= 2
x

8

In [11]:
x = 9

In [12]:
x / 2 

4.5

In [13]:
x % 2 # 나머지

1

In [14]:
y = 2.5

In [15]:
type(2.5)

float

In [16]:
# y를 정수 자료형으로 바꾸려면?
int(y) # from float to integer

2

In [17]:
x = 9 
float(x)

9.0

In [18]:
print(y, y+1, y*2, y**2)

2.5 3.5 5.0 6.25


#### 문자열 (string)

In [19]:
s = "Hello"

In [20]:
print(s)
print(type(s))

Hello
<class 'str'>


In [21]:
len(s)

5

In [22]:
s.upper()

'HELLO'

In [23]:
s.lower()

'hello'

In [24]:
print("My name is {}".format("Groot"))

My name is Groot


In [25]:
print("My name is {} and I'm {} years old".format("Groot", 99))

My name is Groot and I'm 99 years old


In [26]:
print("Hello" + " " + "world")

Hello world


In [27]:
temp = "Python"

In [28]:
temp[0]

'P'

In [29]:
temp[0:4]

'Pyth'

In [30]:
temp = "Python is easy"
temp.split()

['Python', 'is', 'easy']

In [31]:
temp = "Python, is, easy"
temp.split(",")

['Python', ' is', ' easy']

In [32]:
temp = ['Python', 'is', 'easy']
'#'.join(temp)

'Python#is#easy'

In [33]:
' '.join(temp)

'Python is easy'

In [34]:
x = 214
str(x)

'214'

#### 참/거짓 (bool)

In [35]:
t = True
f = False

In [36]:
print(type(t))

<class 'bool'>


In [37]:
print(t and f)

False


In [38]:
print(t or f)

True


In [39]:
print(not t)

False


<br>

#### 2. 함수 (function, method)

In [40]:
def just_print():
    print("Yes, I'm groot")

In [41]:
just_print()

Yes, I'm groot


In [42]:
def add_nums(x, y):
    print(x+y)

In [43]:
add_nums(2, 3)

5


In [44]:
def add_nums(x, y):
    return x+y

In [45]:
a = add_nums(3, 4)

In [46]:
a

7

In [47]:
# Quiz 1. 성과 이름을 받아 이름을 출력해주는 함수 name_creater 만들기

def name_creater(last, first):
    print(last + first)

In [48]:
name_creater("그", "루트")

그루트


In [49]:
# Quiz 2. 다음 함수는 에러를 출력합니다. 어디를 고쳐야할까요?
def drink():
  beverage = "Coke"
  print(beverage)

In [50]:
# Quiz 3. 원의 반지름을 받아 원의 넓이를 Return 해주는 함수 circle_area 만들기 (ㅠ = 3.14)
def circle_area(r):
    return r ** 2 * 3.14

In [51]:
circle_area(10)

314.0

<br>
#### 3. 컨테이너 (다른 변수들을 담을 수 있는 자료형)
list, dict, tuple, set

#### 리스트 (list)

In [52]:
x = [3, 1, 2, 4, 6]
x

[3, 1, 2, 4, 6]

In [53]:
x[0]

3

In [54]:
x[0:3]

[3, 1, 2]

In [55]:
x[1:]

[1, 2, 4, 6]

In [56]:
x[-1]

6

In [57]:
# 리스트 item 추가하기

x.append(10) 
x

[3, 1, 2, 4, 6, 10]

In [58]:
del x[0]
x

[1, 2, 4, 6, 10]

In [59]:
x.remove(4)
x

[1, 2, 6, 10]

In [60]:
# 리스트 합치기
y = [3, 4, 5]
z = x + y
z

[1, 2, 6, 10, 3, 4, 5]

In [61]:
# 리스트 정렬하기
z.sort()
z

[1, 2, 3, 4, 5, 6, 10]

In [62]:
# 리스트 역으로 정렬하기
z.sort(reverse=True)
z

[10, 6, 5, 4, 3, 2, 1]

#### 딕셔너리 (dict)

In [63]:
cage = {'Cat' : '야옹', 'Dog' : '멍멍'}
cage

{'Cat': '야옹', 'Dog': '멍멍'}

In [64]:
cage['Cat']

'야옹'

In [65]:
cage.get('Cat')

'야옹'

In [66]:
cage.get('Fish', '집나감')

'집나감'

In [67]:
print('Pig' in cage)

False


In [68]:
cage['Pig'] = '꿀꿀'
cage

{'Cat': '야옹', 'Dog': '멍멍', 'Pig': '꿀꿀'}

In [69]:
del cage['Pig']
cage

{'Cat': '야옹', 'Dog': '멍멍'}

In [70]:
cage.keys()

dict_keys(['Cat', 'Dog'])

In [71]:
cage.values()

dict_values(['야옹', '멍멍'])

In [72]:
# list -> dict

temp = [['Cat', '야옹'], ['Dog', '멍멍'], ['Tiger', '어흥']]
cage = dict(temp)
cage

{'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

#### 튜플(tuple) 
값과 크기가 변하지 않음

In [73]:
t = (5, 6)
type(t)

tuple

In [74]:
t[0]

5

In [75]:
def return_tuple(x, y):
    return x, y

In [76]:
what = return_tuple(3, 4)
what

(3, 4)

#### 집합(set)
중복을 허용하지 않음

In [77]:
s = {1, 2, 3, 3, 4, 4, 5}
s

{1, 2, 3, 4, 5}

In [78]:
temp = [1, 2, 3, 3, 4, 4, 5]
temp

[1, 2, 3, 3, 4, 4, 5]

In [79]:
what = list(set(temp))
what

[1, 2, 3, 4, 5]

<br>
#### 4. 조건문과 반복문
if, for, while

#### if

In [80]:
def check_price(lunch_price):
    
    price_label = ''
    
    if lunch_price > 10000:
        price_label = "프리미엄 도시락"
    elif lunch_price < 3000: 
        price_label = "저렴이 도시락"
    else: # 나머지 조건 모두 받기
        price_label = "무난무난 도시락"
        
    return price_label

In [81]:
check_price(7000)

'무난무난 도시락'

In [82]:
cage = ['Cat', 'Dog', 'Tiger']

In [83]:
if 'Cat' in cage:
    print('야옹아 이리온')

야옹아 이리온


In [84]:
cage = {'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

In [85]:
if 'Dog' in cage.keys():
    print('치와와는 언제와')

치와와는 언제와


In [86]:
number = 100

In [87]:
if 99 != number:
  print("100점을 못 받았어 ㅠㅠ")

100점을 못 받았어 ㅠㅠ


#### for

In [88]:
nums = [1, 2, 3, 4, 5]

In [89]:
for number in nums:
    print(number)

1
2
3
4
5


In [90]:
range(5)

range(0, 5)

In [91]:
for index in range(5):
    print(index)

0
1
2
3
4


In [92]:
cage = {'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

In [93]:
for item in cage.items():
    print(item)

('Cat', '야옹')
('Dog', '멍멍')
('Tiger', '어흥')


In [94]:
students = ['철수', '영희', '동수'] 

empty_list = []
for student in students:
    empty_list.append(student)

In [95]:
empty_list

['철수', '영희', '동수']

#### while

In [96]:
temp = 1
while temp <= 10:
    print(temp)
    temp += 1

1
2
3
4
5
6
7
8
9
10


In [97]:
# 무한 루프, Pass, Interrupting kernel

#while True:
#    pass

In [98]:
# Quiz 4. 점수(0~100)를 입력으로 받아 학점을 출력해주는 함수 grade를 만드세요.

In [99]:
def grade(score):
    if score > 90:
        print('A')
    elif score > 80:
        print('B')
    elif score > 70:
        print('C')
    else:
        print("F")

In [100]:
grade(87)

B


In [101]:
# Quiz 5. 3개의 숫자를 입력으로 받아, 가장 큰 수를 출력하는 함수 best 를 만드세요. (Hint. 리스트와 sort()를 활용해보세요.)

In [102]:
def best(a, b, c):
    temp = [a, b, c]
    temp.sort(reverse=True)
    print(temp[0])

In [103]:
best(20, 80, 100)

100


In [104]:
# Quiz 6. 숫자 하나를 입력받아, 홀수면 "odd", 짝수면 "even"을 출력하는 함수 odd_or_even을 만드세요. (나머지 연산 명령어는?)

In [105]:
def odd_or_even(x):
    if x % 2 == 0:
        print("even")
    elif x % 2 == 1:
        print("odd")

In [106]:
odd_or_even(9)

odd


In [107]:
# Quiz 7. "20180323sunny" 와 같은 문자열을 입력받아, "Year is 2018, Day is 0323, Weather is sunny" 를 출력하는 함수 weather를 만드세요.

In [108]:
def weather(string):
    print("Year is {}, Day is {}, Weather is {}".format(string[0:4], string[4:8], string[8:]))

In [109]:
weather('20180323still cold')

Year is 2018, Day is 0323, Weather is still cold


<br>

#### 5. 파일 읽고 쓰기

#### 파일 쓰기

In [110]:
file = open('cage.txt', 'w', encoding='utf-8')

In [111]:
cage = ['Cat', 'Dog', 'Tiger']

In [112]:
file.write(str(cage)) # 에러가 발생했어요. 어떻게 해야할까요?

23

In [113]:
for animal in cage:
    file.write(animal)

In [114]:
file.close()

In [115]:
file = open('cage.txt', 'w', encoding='utf-8')

In [116]:
for animal in cage:
    file.write(animal + '\n')

In [117]:
file.close()

In [118]:
# with 과 함께 쓰기

with open('cage.txt', 'w', encoding='utf-8') as file:
    for animal in cage:
        file.write(animal + '\n')

#### 파일 읽기

In [119]:
file = open('cage.txt', 'r', encoding='utf-8')

In [120]:
cage = file.readlines()
cage

['Cat\n', 'Dog\n', 'Tiger\n']

In [121]:
print(cage[0])

Cat



<br>

#### 6. Python 기본 내장함수와 외장함수

In [122]:
len('Python')

6

In [123]:
list('Python')

['P', 'y', 't', 'h', 'o', 'n']

In [124]:
abs(-1.2)

1.2

In [125]:
round(1.7)

2

In [126]:
bool(1)

True

In [127]:
sum([1, 2, 3])

6

In [128]:
max([1, 2, 3])

3

In [129]:
min([1, 2, 3])

1

In [130]:
for num in range(0, 100, 10):
    print(num)

0
10
20
30
40
50
60
70
80
90


In [131]:
def func(x):
    return x**2

In [132]:
func(5)

25

In [133]:
func = lambda x: x**2

In [134]:
func(5)

25

<br>

#### 7. 라이브러리 활용하기 (Library == Package, Module(단일 .py)의 상위 개념 )

In [135]:
import numpy # import 라이브러리이름

In [136]:
a = numpy.array([1, 2, 3])
a

array([1, 2, 3])

In [137]:
import numpy as np # import 라이브러리이름 as 별명

In [138]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [139]:
from numpy import array, ndarray # from 라이브러리이름 import 함수이름

In [140]:
a = array([1, 2, 3])
a

array([1, 2, 3])

In [141]:
import random # 외장함수

x = random.random()
x

0.3835672593291072

In [142]:
x = random.randint(1, 100)
x

7

In [143]:
import os # 외장함수

os.getcwd()

'/content'